import { afterAll, beforeAll, expect, it } from "vitest";
import { execFileSync, spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import type { Database, Json } from "../supabase/database.types";
import { createContentVersionRepository } from "./version-repository";
import { defaultSettings, settingsSchema } from "../business/settings";
import { validateContentVersion } from "./passport";
const enabled = Boolean(process.env.ONEVOICE_LOCAL_ADMIN);
const org = randomUUID(), product = randomUUID(), campaign = randomUUID(), slot = randomUUID(), guide = randomUUID();
const args = ["exec", "-i", "supabase_db_onevoice", "psql", "-X", "-U", "postgres", "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-At"];
const sql = (query: string) => execFileSync("docker", args, { input: query, windowsHide: true, encoding: "utf8" }).trim();
beforeAll(() => { if (enabled) sql(`begin;insert into public.organizations(id,name,slug) values('${org}','Content fixture','${org}');insert into public.business_settings(organization_id,revision,settings) values('${org}',1,'${JSON.stringify(settingsSchema.parse(defaultSettings().settings)).replaceAll("'", "''")}');insert into public.products(id,organization_id,source_url,canonical_url,name,in_stock,stock_quantity,price_vnd,quality,specifications) values('${product}','${org}','urn:test:${product}','urn:test:${product}','Keyboard',true,2,100000,'partial','[{"name":"RAM","value":"16GB"}]');insert into public.campaigns(id,organization_id,title,objective,source_kind,source_ref,priority,source_snapshot,settings_snapshot,timezone) values('${campaign}','${org}','Content fixture','mixed','product','${product}',true,'{}','{}','Asia/Ho_Chi_Minh');insert into public.campaign_slots(id,campaign_id,ordinal) values('${slot}','${campaign}',1);commit;`); });
afterAll(() => { if (enabled) sql(`update public.products set disabled_at=clock_timestamp() where id='${product}';update public.campaigns set status='FAILED' where id='${campaign}';update public.knowledge_sources set document=document||'{"active":false}',version=version+1 where id='${guide}';`); });
it.skipIf(!enabled)("persists full passport through actual REST and fences value drift, competing versions and source-lock waits", async () => {
 const client = createClient<Database>("http://127.0.0.1:54321", process.env.ONEVOICE_LOCAL_ADMIN!, { auth: { persistSession: false, autoRefreshToken: false } });
 const repository = createContentVersionRepository(client, org);
 const evidence = await repository.evidence([{ key: "product", kind: "product", id: product, skuId: product }]);
 const draft = { post: { hook: "Keyboard", caption: "100.000 ₫", cta: "Nhắn tin để được tư vấn" }, script: null, model: { id: "fixture", responseId: null }, claims: [{ field: "post.hook", start: 0, end: 8, kind: "name", sourceKey: "product" }, { field: "post.caption", start: 0, end: 9, kind: "price", sourceKey: "product" }, { field: "post.cta", start: 0, end: 23, kind: "neutral" }] };
 const command = { id: randomUUID(), slotId: slot, requestId: randomUUID(), expectedVersion: 0, draft, evidence };
 expect(evidence.find(item => item.key === "product")?.snapshot.specifications).toEqual({ ram: "16GB" });
 const specDraft = { ...draft, post: { ...draft.post, caption: "RAM: 16GB" }, claims: draft.claims.map(claim => claim.field === "post.caption" ? { ...claim, end: 9, kind: "specification", property: "RAM" } : claim) };
 expect(validateContentVersion(specDraft, evidence, []).validation.status).toBe("VALID");
 sql(`update public.products set price_vnd=200000 where id='${product}';`);
 await expect(repository.save(command)).rejects.toThrow("STALE_CONTENT");
 sql(`update public.products set price_vnd=100000 where id='${product}';`);
 sql(`update public.business_settings set settings=jsonb_set(settings,'{brandVoice}','"Changed voice"') where organization_id='${org}';`);
 await expect(repository.save(command)).rejects.toThrow("STALE_CONTENT");
 sql(`update public.business_settings set settings=jsonb_set(settings,'{brandVoice}',to_jsonb('${defaultSettings().settings.brandVoice}'::text)) where organization_id='${org}';`);
 const result = await repository.save(command); expect(result.version).toBe(1); expect(await repository.save(command)).toEqual(result);
 expect(JSON.parse(sql(`select document->'draft' from public.content_versions where id='${result.id}';`))).toEqual(draft);
 expect(sql(`select (artifact_hash is null)::text from public.content_versions where id='${result.id}';`)).toBe("true");
 await expect(repository.current(result.id)).resolves.toBeTruthy();
 sql(`update public.products set name='Renamed import' where id='${product}';`);
 await expect(repository.current(result.id)).rejects.toThrow("STALE_CONTENT");
 sql(`update public.products set name='Keyboard' where id='${product}';`);
 const competing = await Promise.allSettled([1, 2].map(() => repository.save({ ...command, id: randomUUID(), requestId: randomUUID(), expectedVersion: 1 })));
 expect(competing.filter(item => item.status === "fulfilled")).toHaveLength(1); expect(competing.filter(item => item.status === "rejected")).toHaveLength(1);
 expect(sql(`select count(*) from public.content_versions where slot_id='${slot}';`)).toBe("2");
 expect(sql(`select count(*) from public.audit_events where organization_id='${org}' and action='content.created';`)).toBe("2");
 await expect(repository.current(result.id)).rejects.toThrow("STALE_CONTENT");
 // The writer commits a same-version stock change while content waits for its lock.
 const holder = spawn("docker", args, { windowsHide: true }); let output = "";
 const locked = new Promise<void>(resolve => holder.stdout.on("data", data => { output += data.toString(); if (output.includes("product_locked")) resolve(); }));
 const released = new Promise<void>((resolve, reject) => { holder.on("error", reject); holder.on("exit", code => code === 0 ? resolve() : reject(Error("lock fixture failed"))); });
 holder.stdin.end(`begin;update public.products set stock_quantity=1 where id='${product}';select 'product_locked';select pg_sleep(1);commit;`);
 await locked; await expect(repository.save({ ...command, id: randomUUID(), requestId: randomUUID(), expectedVersion: 2 })).rejects.toThrow("STALE_CONTENT"); await released;
 expect(sql(`select content_revision from public.campaign_slots where id='${slot}';`)).toBe("2");
 const variant = randomUUID();
 sql(`insert into public.product_variants(id,product_id,name,in_stock,stock_quantity,price_vnd,options) values('${variant}','${product}','Variant',true,2,100000,'{"RAM":"32GB"}');`);
 const conflicting = await repository.evidence([{ key: "product", kind: "product", id: product, skuId: variant }]);
 expect(conflicting.find(item => item.key === "product")?.snapshot.specificationConflicts).toBe(true);
 expect(() => validateContentVersion(specDraft, conflicting, [])).toThrow("MISSING_EVIDENCE");
}, 20000);
it.skipIf(!enabled)("preserves external trend provenance and invalidates an obsolete trend run", async () => {
 const run = randomUUID(), trendCampaign = randomUUID(), trendSlot = randomUUID();
 const now = new Date(), topic = "Bàn phím", fingerprint = "a".repeat(64);
 const observation = { fingerprint, topic, url: "https://example.com/story", sourceTimestamp: now.toISOString(), timestampKind: "published", expiresAt: new Date(now.getTime() + 900000).toISOString(), trust: "untrusted_external", metrics: null };
 const batch = { observedAt: now.toISOString(), capabilities: { social: "unconfigured", news: "available", facebook: "unavailable" }, sources: [{ key: "fixture", kind: "rss_news", url: "https://example.com/rss", ttlSeconds: 900, status: "success", errorCode: null, observations: [observation] }] };
 const client = createClient<Database>("http://127.0.0.1:54321", process.env.ONEVOICE_LOCAL_ADMIN!, { auth: { persistSession: false, autoRefreshToken: false } });
 expect((await client.rpc("record_trend_ingestion", { p_organization_id: org, p_run_id: run, p_batch: batch as Json })).error).toBeNull();
 sql(`update public.business_settings set settings=jsonb_set(settings,'{allowedTopics}','["Bàn phím"]') where organization_id='${org}';insert into public.campaigns(id,organization_id,title,objective,source_kind,source_ref,priority,source_snapshot,settings_snapshot,timezone,decision) values('${trendCampaign}','${org}','Trend fixture','engagement','trend','fixture',false,'${JSON.stringify({ runId: run, observation })}','{}','Asia/Ho_Chi_Minh','{}');insert into public.campaign_slots(id,campaign_id,ordinal) values('${trendSlot}','${trendCampaign}',1);`);
 try {
  const repository = createContentVersionRepository(client, org), evidence = await repository.evidence([{ key: "trend", kind: "trend", id: run, fingerprint }]);
  const hook = `Chủ đề tham khảo: ${topic}`, phrase = "Nhắn tin để được tư vấn";
  const draft = { post: { hook, caption: phrase, cta: phrase }, script: null, model: { id: "fixture", responseId: null }, claims: [{ field: "post.hook", start: 0, end: hook.length, kind: "trend", sourceKey: "trend" }, ...["post.caption", "post.cta"].map(field => ({ field, start: 0, end: phrase.length, kind: "neutral" }))] };
  const result = await repository.save({ id: randomUUID(), slotId: trendSlot, requestId: randomUUID(), expectedVersion: 0, draft, evidence });
  await expect(repository.current(result.id)).resolves.toBeTruthy();
  expect((await client.rpc("record_trend_ingestion", { p_organization_id: org, p_run_id: randomUUID(), p_batch: { observedAt: new Date().toISOString(), capabilities: { social: "unconfigured", news: "unconfigured", facebook: "unavailable" }, sources: [] } })).error).toBeNull();
  await expect(repository.current(result.id)).rejects.toThrow("STALE_CONTENT");
 } finally { sql(`update public.campaigns set status='FAILED' where id='${trendCampaign}';`); }
}, 20000);
it.skipIf(!enabled)("stores configured descriptive provenance and rejects refreshed hashes or disabled sources", async () => {
 const guideSlot = randomUUID(), firstRun = randomUUID(), secondRun = randomUUID();
 sql(`insert into public.campaign_slots(id,campaign_id,ordinal) values('${guideSlot}','${campaign}',2);insert into public.knowledge_sources(id,organization_id,version,document) values('${guide}','${org}',1,'{"name":"Guide","kind":"text","text":"Thiết kế gọn nhẹ","url":null,"authority":"business","productIds":["${product}"],"topics":[],"freshnessHours":1,"active":true}');`);
 const ingest = (run: string, cycle: number, hash: string) => sql(`insert into public.knowledge_ingestion_runs(id,organization_id,source_id,source_version,refresh_cycle) values('${run}','${org}','${guide}',1,${cycle});insert into public.knowledge_ingestions(id,organization_id,source_id,source_version,source_document,content_hash,content_type,fetched_at,expires_at) select '${run}','${org}','${guide}',1,document,repeat('${hash}',64),'text/plain',clock_timestamp(),clock_timestamp()+interval '1 hour' from public.knowledge_sources where id='${guide}';insert into public.knowledge_chunks(ingestion_id,ordinal,body) values('${run}',1,'Thiết kế gọn nhẹ');`);
 ingest(firstRun, 1, "a");
 const client = createClient<Database>("http://127.0.0.1:54321", process.env.ONEVOICE_LOCAL_ADMIN!, { auth: { persistSession: false, autoRefreshToken: false } });
 const repository = createContentVersionRepository(client, org);
 const variant = sql(`select id from public.product_variants where product_id='${product}' limit 1;`);
 const evidence = await repository.evidence([{ key: "product", kind: "product", id: product, skuId: variant }, { key: "guide", kind: "knowledge", id: guide }]);
 const hook = "Theo Guide: “Thiết kế gọn nhẹ”", cta = "Nhắn tin để được tư vấn";
 const draft = { post: { hook, caption: "100.000 ₫", cta }, script: null, model: { id: "fixture", responseId: null }, claims: [{ field: "post.hook", start: 0, end: hook.length, kind: "knowledge", sourceKey: "guide", quote: "Thiết kế gọn nhẹ" }, { field: "post.caption", start: 0, end: 9, kind: "price", sourceKey: "product" }, { field: "post.cta", start: 0, end: cta.length, kind: "neutral" }] };
 const saved = await repository.save({ id: randomUUID(), slotId: guideSlot, requestId: randomUUID(), expectedVersion: 0, draft, evidence });
 await expect(repository.current(saved.id)).resolves.toBeTruthy();
 ingest(secondRun, 2, "b");
 await expect(repository.current(saved.id)).rejects.toThrow("STALE_CONTENT");
 sql(`update public.knowledge_sources set document=document||'{"active":false}' where id='${guide}';`);
 await expect(repository.evidence([{ key: "guide", kind: "knowledge", id: guide }])).rejects.toThrow("STALE_CONTENT");
}, 20000);
