// SPDX-License-Identifier: Apache-2.0
"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { allowedWarrantyTransition, warrantyCommandSchema, warrantyStatuses, type EligibleItem, type WarrantyPage, type WarrantyRecord, type WarrantyStatus } from "@/lib/warranty/management";
import styles from "./warranty.module.css";
const labels: Record<WarrantyStatus, string> = { RECEIVED: "Đã tiếp nhận", INSPECTING: "Đang kiểm tra", IN_SERVICE: "Đang xử lý", READY: "Sẵn sàng trả khách", COMPLETED: "Đã hoàn tất" };
type Draft = { id: string; orderId: string; lineNumber: number; version: number; status: WarrantyStatus; customerNote: string; privateNote: string; productName: string; buyerName: string | null };
const time = (value: string) => new Date(value).toLocaleString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" });
export function WarrantyManager({ initial }: { initial: WarrantyPage }) {
 const [page, setPage] = useState(initial), [search, setSearch] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
 const [draft, setDraft] = useState<Draft | null>(null), [record, setRecord] = useState<WarrantyRecord | null>(null), [creating, setCreating] = useState(false);
 const [orderSearch, setOrderSearch] = useState(""), [items, setItems] = useState<EligibleItem[]>([]), [orderPage, setOrderPage] = useState(1);
 const retry = useRef<{ serialized: string; requestId: string } | null>(null);
 async function request(url: string, init?: RequestInit) { const result = await fetch(url, { ...init, cache: "no-store" }); if (!result.ok) throw Error(result.status === 409 ? "Nội dung đã đổi ở phiên khác. Bản nháp vẫn được giữ; tải lại hồ sơ trước khi sửa tiếp." : result.status === 400 ? "Không thể lưu: kiểm tra dữ liệu, tiến độ và điều kiện đơn đã thanh toán, giao thành công." : "Không thực hiện được. Kiểm tra phiên đăng nhập và thử lại."); return result.json(); }
 async function run(work: () => Promise<void>) { setBusy(true); setNotice(""); try { await work(); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
 async function load(number = 1) { setPage(await request(`/api/warranty?${new URLSearchParams({ search, page: String(number) })}`)); }
 async function open(id: string) { const value: WarrantyRecord = await request(`/api/warranty?id=${id}`); setRecord(value); setDraft(value); setCreating(false); retry.current = null; }
 async function findOrders(number = 1) { setItems(await request(`/api/warranty?${new URLSearchParams({ orders: "true", search: orderSearch, page: String(number) })}`)); setOrderPage(number); }
 function choose(item: EligibleItem) { setDraft({ id: crypto.randomUUID(), orderId: item.orderId, lineNumber: item.lineNumber, version: 0, status: "RECEIVED", customerNote: "", privateNote: "", productName: item.productName, buyerName: item.buyerName }); setRecord(null); setCreating(false); retry.current = null; }
 async function save() {
  if (!draft) return;
  const value = { id: draft.id, orderId: draft.orderId, lineNumber: draft.lineNumber, expectedVersion: draft.version, status: draft.status, customerNote: draft.customerNote, privateNote: draft.privateNote };
  const serialized = JSON.stringify(value); if (retry.current?.serialized !== serialized) retry.current = { serialized, requestId: crypto.randomUUID() };
  const parsed = warrantyCommandSchema.safeParse({ ...value, requestId: retry.current.requestId }); if (!parsed.success) throw Error(parsed.error.issues[0]?.message ?? "Dữ liệu không hợp lệ.");
  await request("/api/warranty", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(parsed.data) });
  await open(draft.id); await load(page.page); setNotice("Đã lưu tiến độ. Ghi chú nội bộ chỉ dành cho nhân viên.");
 }
 return <section className={styles.page}><header><Link href="/support">← Yêu cầu hỗ trợ</Link><h1>Theo dõi bảo hành</h1><p>Nhân viên tạo hồ sơ sau khi tiếp nhận yêu cầu. Chỉ chọn sản phẩm thuộc đơn đã thanh toán và giao thành công.</p></header>
  <div className={styles.toolbar}><input aria-label="Tìm hồ sơ bảo hành" placeholder="Tên khách, sản phẩm hoặc SKU" maxLength={100} value={search} onChange={e => setSearch(e.target.value)} /><button disabled={busy} onClick={() => void run(() => load())}>Tìm / tải lại</button><button disabled={busy} onClick={() => void run(async () => { setCreating(true); setDraft(null); setRecord(null); await findOrders(); })}>Tạo hồ sơ</button></div>
  {notice && <p role="status" className={styles.notice}>{notice}</p>}
  <div className={styles.columns}><aside><p>{page.total} hồ sơ · Trang {page.page}</p>{page.items.length === 0 && <p>Chưa có hồ sơ trong bộ lọc này.</p>}{page.items.map(item => <button className={styles.ticket} key={item.id} disabled={busy} onClick={() => void run(() => open(item.id))}><strong>{item.productName}</strong><span>{item.buyerName ?? "Chưa có tên khách"} · {labels[item.status]}</span><small>{time(item.updatedAt)} · Phiên bản {item.version}</small></button>)}<div className={styles.toolbar}><button disabled={busy || page.page <= 1} onClick={() => void run(() => load(page.page - 1))}>Trước</button><button disabled={busy || page.page * 20 >= page.total} onClick={() => void run(() => load(page.page + 1))}>Sau</button></div></aside>
  <div>{creating && <div className={styles.panel}><h2>Chọn đơn và sản phẩm</h2><p>Đơn chưa thanh toán hoặc chưa giao xong không xuất hiện. Việc tạo hồ sơ không tự phê duyệt quyền lợi bảo hành.</p><div className={styles.toolbar}><input aria-label="Tìm đơn đủ điều kiện" placeholder="Tên khách, sản phẩm hoặc SKU" maxLength={100} value={orderSearch} onChange={e => setOrderSearch(e.target.value)} /><button disabled={busy} onClick={() => void run(() => findOrders())}>Tìm đơn</button></div>{items.length === 0 && <p>Không có sản phẩm đủ điều kiện trong bộ lọc này.</p>}{items.map(item => <button className={styles.ticket} disabled={busy} key={`${item.orderId}:${item.lineNumber}`} onClick={() => choose(item)}><strong>{item.productName} {item.sku ? `· ${item.sku}` : ""}</strong><span>{item.buyerName ?? "Chưa có tên khách"} · Số lượng {item.quantity}</span><small>Đặt ngày {time(item.orderedAt)} · Dòng {item.lineNumber} · Mã đơn …{item.orderId.slice(-8)}</small></button>)}<div className={styles.toolbar}><button disabled={busy || orderPage === 1} onClick={() => void run(() => findOrders(orderPage - 1))}>Đơn trước</button><button disabled={busy || items.length < 20} onClick={() => void run(() => findOrders(orderPage + 1))}>Đơn tiếp</button></div></div>}
  {draft && <form className={styles.panel} onSubmit={e => { e.preventDefault(); void run(save); }}><h2>{draft.version ? "Cập nhật hồ sơ" : "Hồ sơ mới"}</h2><p><strong>{draft.productName}</strong> · {draft.buyerName ?? "Chưa có tên khách"}</p><p>Dòng {draft.lineNumber} · Mã đơn …{draft.orderId.slice(-8)}</p><fieldset disabled={busy}><label>Tiến độ<select value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value as WarrantyStatus })}>{warrantyStatuses.filter(status => record ? allowedWarrantyTransition(record.status, status) : status === "RECEIVED").map(status => <option key={status} value={status}>{labels[status]}</option>)}</select></label><label>Ghi chú cho khách<textarea rows={4} maxLength={4000} value={draft.customerNote} onChange={e => setDraft({ ...draft, customerNote: e.target.value })} /></label><p>Khách và trợ lý có thể xem phần này khi tra cứu đúng đơn.</p><label>Ghi chú nội bộ · chỉ nhân viên<textarea rows={4} maxLength={4000} value={draft.privateNote} onChange={e => setDraft({ ...draft, privateNote: e.target.value })} /></label></fieldset><div className={styles.toolbar}><button disabled={busy} type="submit">Lưu tiến độ</button>{record && <button disabled={busy} type="button" onClick={() => void run(() => open(record.id))}>Tải lại hồ sơ</button>}</div>
   {record && <div><h3>Lịch sử tiến độ · 100 phiên bản gần nhất</h3><p>Thời gian Việt Nam (UTC+7).</p>{record.history.map(entry => <details key={entry.version}><summary>{labels[entry.status]} · {time(entry.createdAt)} · v{entry.version}</summary><p className={styles.text}>Cho khách: {entry.customerNote || "Chưa có ghi chú"}</p><p className={styles.text}>Nội bộ: {entry.privateNote || "Chưa có ghi chú"}</p></details>)}</div>}
  </form>}{!creating && !draft && <p>Chọn hồ sơ để xem chi tiết hoặc tạo hồ sơ mới.</p>}</div></div></section>;
}
