// SPDX-License-Identifier: Apache-2.0
"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import type { Campaign, CampaignPage, ManualCampaign } from "@/lib/campaigns/management";
import styles from "./campaigns.module.css";
const states: Record<string, string> = { PLANNED: "Đang chuẩn bị", ACTIVE: "Đang thực hiện", COMPLETED: "Đã hoàn tất", FAILED: "Đã dừng do lỗi", READY: "Đã sẵn sàng", CLAIMED: "Đang xử lý", PUBLISHED: "Đã đăng", SKIPPED: "Đã bỏ qua" };
const objectives = { engagement: "Tăng tương tác", messages: "Tăng tin nhắn", "paid-orders": "Tăng đơn hàng", mixed: "Kết hợp" };
export function CampaignManager({ initial, canManage }: { initial: CampaignPage; canManage: boolean }) {
 const [list, setList] = useState(initial), [detail, setDetail] = useState<Campaign | null>(null), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
 const [kind, setKind] = useState<"product" | "program">("product"), [search, setSearch] = useState(""), [choices, setChoices] = useState<Array<{ id: string; name: string }>>([]), [selected, setSelected] = useState(""), [objective, setObjective] = useState<ManualCampaign["objective"]>("mixed");
 const retry = useRef<{ serialized: string; id: string; requestId: string } | null>(null);
 async function read(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, cache: "no-store" }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw Error(body.error === "SETTINGS_REQUIRED" ? "Cần lưu cấu hình doanh nghiệp trước khi tạo chiến dịch." : response.status === 409 ? "Trạng thái đã thay đổi hoặc đang có yêu cầu ưu tiên. Tải lại danh sách trước khi thử lại." : "Không thực hiện được. Kiểm tra dữ liệu, phiên đăng nhập và thử lại."); } return response.json(); }
 async function run(work: () => Promise<void>) { setBusy(true); setNotice(""); try { await work(); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
 async function load(page = list.page) { setList(await read(`/api/campaigns?page=${page}`)); }
 async function find() { const data = await read(kind === "product" ? `/api/products/manage?active=active&pageSize=20&search=${encodeURIComponent(search)}` : `/api/knowledge?kind=promotion&pageSize=20&search=${encodeURIComponent(search)}`); setChoices(data.items.map((item: { id: string; name?: string; document?: { title: string } }) => ({ id: item.id, name: item.name ?? item.document?.title ?? "Nội dung" }))); }
 async function create() {
  const command = { expectedControlRevision: list.control.revision, sourceKind: kind, sourceId: selected, objective }; const serialized = JSON.stringify(command);
  if (retry.current?.serialized !== serialized) retry.current = { serialized, id: crypto.randomUUID(), requestId: crypto.randomUUID() };
  const result = await read("/api/campaigns", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...command, id: retry.current.id, requestId: retry.current.requestId }) });
  await load(1); setDetail(await read(`/api/campaigns?id=${result.id}`)); retry.current = null; setNotice("Đã tạo yêu cầu ưu tiên và tạm dừng tự động. Hoàn tất yêu cầu không tự bật lại.");
 }
 const dated = list.items.flatMap(item => item.slots.filter(slot => slot.scheduledAt).map(slot => ({ item, slot })));
 return <section className={styles.page}><header><Link href="/catalog">← Danh mục</Link><h1>Chiến dịch và lịch nội dung</h1><p>Tự động: <strong>{list.control.status === "PAUSED" ? "Đang tạm dừng" : "Đang chạy"}</strong>{list.control.priorityId ? " · Có yêu cầu ưu tiên đang thực hiện" : ""}.</p><p>Yêu cầu mới được lưu ở trạng thái chuẩn bị. Việc tạo chiến dịch chưa tạo nội dung, chọn giờ hay đăng bài.</p></header>
  {notice && <p role="status" className={styles.notice}>{notice}</p>}
  {canManage && <section className={styles.panel}><h2>Yêu cầu ưu tiên</h2><p>Tạo yêu cầu sẽ tạm dừng hoạt động tự động. Sản phẩm phải có giá/tồn kho xác thực; chương trình phải còn hiệu lực.</p><div className={styles.actions}><select aria-label="Loại yêu cầu ưu tiên" value={kind} disabled={busy} onChange={e => { setKind(e.target.value as "product" | "program"); setChoices([]); setSelected(""); }}><option value="product">Sản phẩm</option><option value="program">Chương trình</option></select><input aria-label="Tìm sản phẩm hoặc chương trình" placeholder="Tìm theo tên" maxLength={100} value={search} onChange={e => setSearch(e.target.value)} /><button disabled={busy} onClick={() => void run(find)}>Tìm</button></div><div className={styles.actions}><select aria-label="Chọn sản phẩm hoặc chương trình" value={selected} onChange={e => setSelected(e.target.value)} disabled={busy}><option value="">Chọn nội dung ưu tiên…</option>{choices.map(choice => <option key={choice.id} value={choice.id}>{choice.name}</option>)}</select><select aria-label="Mục tiêu chiến dịch" value={objective} onChange={e => setObjective(e.target.value as ManualCampaign["objective"])} disabled={busy}>{Object.entries(objectives).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><button disabled={busy || !selected || !!list.control.priorityId} onClick={() => void run(create)}>Tạo yêu cầu và tạm dừng</button></div><Link href="/settings">Cấu hình doanh nghiệp →</Link></section>}
  <div className={styles.columns}><section className={styles.panel}><h2>Chiến dịch</h2><p>{list.total} chiến dịch · Trang {list.page}</p><button disabled={busy} onClick={() => void run(() => load())}>Tải lại</button>{list.items.length === 0 && <p>Chưa có chiến dịch.</p>}{list.items.map(item => <button className={styles.ticket} disabled={busy} key={item.id} onClick={() => void run(async () => { setDetail(await read(`/api/campaigns?id=${item.id}`)); })}><strong>{item.title}</strong><span>{item.priority ? "Ưu tiên" : "Đề xuất tự động"} · {states[item.status]}</span></button>)}<div className={styles.actions}><button disabled={busy || list.page === 1} onClick={() => void run(() => load(list.page - 1))}>Trước</button><button disabled={busy || list.page * 20 >= list.total} onClick={() => void run(() => load(list.page + 1))}>Sau</button></div></section>
  <section className={styles.panel}><h2>Chi tiết</h2>{detail ? <><h3>{detail.title}</h3><p>{objectives[detail.objective as keyof typeof objectives]} · {states[detail.status]}</p><p>Tạo lúc {new Date(detail.createdAt).toLocaleString("vi-VN", { timeZone: detail.timezone })} ({detail.timezone}).</p>{detail.slots.map(slot => <p key={slot.id}>Nội dung {slot.ordinal}: {states[slot.status]} · {slot.scheduledAt ? new Date(slot.scheduledAt).toLocaleString("vi-VN", { timeZone: detail.timezone }) : "Chưa chọn giờ"} · {slot.contentVersionId ? "Đã có nội dung" : "Chưa có nội dung"}</p>)}<p>Nguồn và điều kiện tại lúc tạo đã được lưu. Trước khi đăng, hệ thống vẫn phải kiểm tra dữ liệu mới nhất.</p></> : <p>Chọn chiến dịch để xem thông tin.</p>}</section></div>
  <section className={styles.panel}><h2>Lịch nội dung · các chiến dịch trong trang này</h2>{dated.length ? dated.sort((a, b) => a.slot.scheduledAt!.localeCompare(b.slot.scheduledAt!)).map(({ item, slot }) => <p key={slot.id}>{new Date(slot.scheduledAt!).toLocaleString("vi-VN", { timeZone: item.timezone })} ({item.timezone}) · {item.title} · {states[slot.status]}</p>) : <p>Chưa có khung giờ đăng. Chiến dịch đang chuẩn bị nằm trong danh sách phía trên.</p>}</section>
 </section>;
}
