// SPDX-License-Identifier: Apache-2.0
"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback,useEffect,useRef,useState } from "react";
import type { SupportDetail,SupportMessage } from "@/lib/conversations/support/read";
import styles from "./support.module.css";
import { claimantLabel } from "./claimant-label";
function mergeMessages(old:SupportMessage[],fresh:SupportMessage[]){const items=new Map(old.map(item=>[item.id,item]));fresh.forEach(item=>items.set(item.id,item));return [...items.values()].sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt)||b.id.localeCompare(a.id));}
export function SupportConversation({initial,viewer}:{initial:SupportDetail;viewer:{id:string;role:string}}){
 const router=useRouter();
 const [detail,setDetail]=useState(initial);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [assignee,setAssignee]=useState("");const [loadingOlder,setLoadingOlder]=useState(false);
 const epoch=useRef(0);const inFlight=useRef(false);const olderLoaded=useRef(false);const retry=useRef<{body:string;id:string}|null>(null);
 const refresh=useCallback(async()=>{const current=++epoch.current;const response=await fetch(`/api/support/${initial.id}`,{cache:"no-store"});if(response.status===401||response.status===403){router.push("/login");return;}if(!response.ok)throw Error("refresh_failed");const payload=await response.json() as {detail:SupportDetail};if(current===epoch.current)setDetail(previous=>({...payload.detail,messages:mergeMessages(previous.messages,payload.detail.messages),nextCursor:olderLoaded.current?previous.nextCursor:payload.detail.nextCursor}));},[initial.id,router]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==="visible"&&!inFlight.current)void refresh().catch(()=>setNotice("Chưa thể cập nhật. Nội dung gần nhất vẫn được giữ; bấm Làm mới để thử lại."));},10000);return()=>{clearInterval(timer);};},[refresh]);
 async function transition(operation:"claim"|"complete"|"reassign"){
  if(inFlight.current)return;inFlight.current=true;setBusy(true);setNotice("");epoch.current++;
  const input={operation,expectedRevision:detail.revision,...(operation==="reassign"?{assigneeId:assignee}:{})};const body=JSON.stringify(input);if(retry.current?.body!==body)retry.current={body,id:crypto.randomUUID()};
  try{const response=await fetch(`/api/support/${detail.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...input,requestId:retry.current.id})});
   if(response.status===409){retry.current=null;await refresh();setNotice("Yêu cầu vừa được cập nhật bởi người khác. Đã tải trạng thái mới; hãy kiểm tra người nhận trước khi thao tác lại.");return;}
   if(!response.ok){if(response.status===403)await refresh();setNotice(response.status===403?"Bạn không có quyền thực hiện thao tác này. Trạng thái hiện tại đã được cập nhật.":"Chưa thể lưu thao tác. Bạn có thể thử lại cùng yêu cầu.");return;}
   retry.current=null;await refresh();setNotice(operation==="complete"?"Đã hoàn tất. Chỉ tin nhắn mới nhận sau thời điểm này được phép xử lý tự động.":operation==="claim"?"Bạn đã nhận yêu cầu. Mở hộp thư Meta để trả lời khách.":"Đã chuyển người nhận và ghi nhật ký; hội thoại vẫn tạm dừng AI.");
  }catch{setNotice("Kết nối gián đoạn. Thử lại thao tác sẽ dùng cùng mã yêu cầu để tránh ghi hai lần.");}finally{inFlight.current=false;setBusy(false);}
 }
 async function older(){if(!detail.nextCursor||loadingOlder)return;setLoadingOlder(true);try{const response=await fetch(`/api/support/${detail.id}?cursor=${encodeURIComponent(detail.nextCursor)}`,{cache:"no-store"});if(!response.ok)throw Error("history_failed");const payload=await response.json() as {detail:SupportDetail};olderLoaded.current=true;setDetail(previous=>({...previous,messages:mergeMessages(previous.messages,payload.detail.messages),nextCursor:payload.detail.nextCursor}));}catch{setNotice("Chưa thể tải tin nhắn cũ. Vui lòng thử lại.");}finally{setLoadingOlder(false);}}
 const canComplete=detail.status==="STAFF_ACTIVE"&&(viewer.role==="manager"||detail.handoff?.claimedBy===viewer.id);
 return <section className={styles.page}><Link href="/support">← Hàng chờ hỗ trợ</Link><header className={styles.header}><div><p className={styles.eyebrow}>HỘI THOẠI MESSENGER</p><h1>Khách {detail.psid}</h1><p>Page {detail.pageId} · Phiên bản {detail.revision}</p></div><button type="button" disabled={busy} onClick={()=>void refresh().catch(()=>setNotice("Chưa thể cập nhật. Vui lòng thử lại."))}>Làm mới</button></header>
 <div className={styles.context}><div><span className={styles.badge}>{detail.status==="WAITING_STAFF"?"Chờ nhận":detail.status==="STAFF_ACTIVE"?"Đang xử lý":"Đã hoàn tất"}</span><p>{detail.handoff?.claimedBy?`Người nhận: ${claimantLabel(detail.handoff.claimedBy,viewer.id,detail.assignees)}`:detail.status==="WAITING_STAFF"?"Chưa có nhân viên nhận yêu cầu.":"Yêu cầu hỗ trợ đã hoàn tất."}</p><p>Trả lời khách trong hộp thư Meta. Việc trả lời bên Meta không tự đánh dấu hoàn tất ở đây.</p></div><div className={styles.actions}>{detail.status==="WAITING_STAFF"&&<button disabled={busy} onClick={()=>void transition("claim")}>Nhận yêu cầu</button>}{canComplete&&<button disabled={busy} onClick={()=>void transition("complete")}>Đánh dấu đã xử lý</button>}{detail.inboxUrl&&<a href={detail.inboxUrl} target="_blank" rel="noopener noreferrer">Mở hộp thư Meta ↗</a>}</div></div>
 <p className={styles.notice}>{detail.inboxUrl?"Liên kết mở hộp thư Page, không bảo đảm chọn đúng cuộc chat.":"Chưa cấu hình liên kết hộp thư Meta."} Mở Meta Business Suite → Hộp thư, chọn Page {detail.pageId} và tìm hội thoại phù hợp. PSID để đối chiếu: {detail.psid}.</p>
 {viewer.role==="manager"&&detail.status==="STAFF_ACTIVE"&&<div className={styles.reassign}><label>Chuyển người nhận<select value={assignee} disabled={busy} onChange={event=>setAssignee(event.target.value)}><option value="">Chọn nhân viên đang hoạt động</option>{detail.assignees.filter(actor=>actor.id!==detail.handoff?.claimedBy).map(actor=><option key={actor.id} value={actor.id}>{actor.name}</option>)}</select></label><button disabled={busy||!assignee} onClick={()=>void transition("reassign")}>Chuyển người nhận</button></div>}
 {notice&&<p className={styles.notice} role="status">{notice}</p>}
 <section aria-label="Lịch sử tin nhắn"><div className={styles.header}><h2>Tin nhắn gần nhất</h2><span>Tự cập nhật mỗi 10 giây · giờ UTC</span></div>{detail.messages.length===0&&<p>Chưa có tin nhắn đã được ghi vào hội thoại.</p>}<div className={styles.messages}>{detail.messages.map(message=><article key={message.id} className={styles.message}><header><strong>{message.kind==="message"?"Khách hàng":message.kind==="postback"?"Thao tác của khách":"Nguồn giới thiệu"}</strong><time dateTime={message.receivedAt}>{new Date(message.receivedAt).toLocaleString("vi-VN",{timeZone:"UTC"})} UTC</time></header>{message.text&&<p className={styles.messageText}>{message.text}</p>}{message.attachments.map((attachment,index)=><p key={index}>{attachment.url?<a href={attachment.url} target="_blank" rel="noopener noreferrer">Mở tệp đính kèm ({attachment.type}) ↗</a>:<>Tệp đính kèm ({attachment.type}) · không có liên kết an toàn</>}</p>)}{!message.text&&message.attachments.length===0&&<p>Sự kiện không có nội dung văn bản.</p>}</article>)}</div>{detail.nextCursor&&<button className={styles.next} disabled={loadingOlder} onClick={()=>void older()}>{loadingOlder?"Đang tải…":"Xem tin nhắn cũ hơn"}</button>}</section>
 </section>;
}
