import { describe,expect,it,vi } from "vitest";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/lib/supabase/database.types";
import { evidenceQuerySchema,createEvidenceLookup,productEvidence } from "./evidence";
const org="a0000000-0000-0000-0000-000000000001",id="d1600000-0000-0000-0000-000000000001",variant="d1600000-0000-0000-0000-000000000002";
const row={productId:id,variantId:variant,version:3,variantUpdatedAt:"2026-09-12T00:00:00Z",name:"Laptop / 16GB",sku:"SKU16",brand:"Fixture",productType:"laptop",priceVnd:10000000,stockQuantity:2,inStock:true,specificationsComplete:true,specifications:[{name:"RAM",value:"16GB",scope:"variant"}],updatedAt:"2026-09-12T00:00:00Z"};
describe("structured consultation evidence",()=>{
 it("strictly bounds parameters and rejects scope/SQL operator injection",()=>{expect(evidenceQuerySchema.safeParse({operation:"search_products",organizationId:org}).success).toBe(false);expect(evidenceQuerySchema.safeParse({operation:"search_products",limit:1000}).success).toBe(false);expect(evidenceQuerySchema.safeParse({operation:"compare_products",items:[{productId:id,variantId:variant,expectedSku:"SKU16"}]}).success).toBe(true);});
 it("asks for missing needs without fabricating catalog results",async()=>{const rpc=vi.fn();const result=await createEvidenceLookup({rpc} as unknown as SupabaseClient<Database>).lookup(org,{operation:"search_products"});expect(result.missing).toContain("need_required");expect(rpc).not.toHaveBeenCalled();});
 it("ties every product fact to exact product+variant/version/asOf",()=>{const result=productEvidence(row,"2026-09-12T10:00:00Z");expect(result.availability).toBe("available");expect(result.facts.every(f=>f.evidence.productId===id && f.evidence.variantId===variant && f.evidence.version===3 && f.evidence.asOf==="2026-09-12T10:00:00Z")).toBe(true);});
 it("does not mistake an unknown physical quantity for available stock",()=>{const result=productEvidence({...row,stockQuantity:null},"2026-09-12T10:00:00Z");expect(result.availability).toBe("unknown");expect(result.missing).toContain("stock_quantity");});
 it.each([-1,0.5,Number.MAX_SAFE_INTEGER+1])("invalid physical quantity %s cannot verify availability",stockQuantity=>{const result=productEvidence({...row,stockQuantity,inStock:true},"2026-09-12T10:00:00Z");expect(result.availability).toBe("unknown");expect(result.missing).toContain("stock_quantity");expect(result.missing).toContain("verified_availability");expect(result.facts.some(f=>f.field==="stock_quantity")).toBe(false);});
 it("conflicting specs become missing rather than selecting a favorable value",()=>{const result=productEvidence({...row,specifications:[{name:"RAM",value:"8GB",scope:"product"},{name:"RAM",value:"16GB",scope:"variant"}]},"2026-09-12T10:00:00Z");expect(result.missing).toContain("conflicting_spec:ram");expect(result.facts.some(f=>f.field==="spec:ram")).toBe(false);});
 it("incomplete specs never become verified claims",()=>{const result=productEvidence({...row,specificationsComplete:false},"2026-09-12T10:00:00Z");expect(result.missing).toContain("specifications_incomplete");expect(result.facts.some(f=>f.field.startsWith("spec:"))).toBe(false);});
 it("uses only one scoped read RPC and normalizes storage errors",async()=>{const rpc=vi.fn().mockReturnValue({abortSignal:()=>Promise.resolve({data:null,error:{message:"private database body"}})});await expect(createEvidenceLookup({rpc} as unknown as SupabaseClient<Database>).lookup(org,{operation:"search_products",need:"laptop"})).rejects.toThrow("evidence_unavailable");expect(rpc.mock.calls[0][1].p_organization_id).toBe(org);});
 it("marks conflicting policy bodies instead of choosing one and never combines discounts",async()=>{
  const policy={id,kind:"warranty",title:"Warranty",body:"One year",source:"business_policy",version:1,asOf:"2026-09-12T10:00:00Z",startsAt:null,expiresAt:null,productId:id,trust:"canonical_business_data"};
  const rpc=vi.fn().mockReturnValue({abortSignal:()=>Promise.resolve({error:null,data:{asOf:policy.asOf,policies:[policy,{...policy,id:variant,body:"Two years"}]}})});
  const result=await createEvidenceLookup({rpc} as unknown as SupabaseClient<Database>).lookup(org,{operation:"read_guidance",productId:id});expect(result.policies).toEqual([]);expect(result.missing).toContain("conflicting_policy:warranty");
 });
});
