import { afterAll, beforeAll, expect, it } from "vitest";
import { execFileSync, spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import type { Database, Json } from "../supabase/database.types";
import { defaultSettings, settingsSchema } from "../business/settings";
import { readOpportunityInput } from "../opportunities/snapshot";
import { rankOpportunities } from "../opportunities/engine";
import { createCampaignService } from "./repository";
const enabled = Boolean(process.env.ONEVOICE_LOCAL_ADMIN);
const org = randomUUID(), product = randomUUID(), program = randomUUID();
const sql = (query: string) => execFileSync("docker", ["exec", "-i", "supabase_db_onevoice", "psql", "-X", "-U", "postgres", "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-At"], { input: query, windowsHide: true, encoding: "utf8" }).trim();
beforeAll(() => {
 if (!enabled) return;
 const settings = JSON.stringify(settingsSchema.parse(defaultSettings().settings)).replaceAll("'", "''");
 sql(`begin; insert into public.organizations(id,name,slug) values('${org}','Campaign local fixture','campaign-${org}'); insert into public.business_settings(organization_id,revision,settings) values('${org}',1,'${settings}'); insert into public.marketing_control(organization_id,status) values('${org}','RUNNING'); insert into public.products(id,organization_id,source_url,canonical_url,name,in_stock,stock_quantity,price_vnd,quality) values('${product}','${org}','urn:test:${product}','urn:test:${product}','Local keyboard',true,2,500000,'partial'); insert into public.promotions(id,organization_id,label,scope,discount_type,discount_value) values('${program}','${org}','Local offer','all','percent',10); commit;`);
});
afterAll(() => { if (enabled) sql(`update public.marketing_control set status='PAUSED',reason='fixture_complete' where organization_id='${org}'; update public.products set disabled_at=clock_timestamp() where id='${product}'; update public.promotions set disabled_at=clock_timestamp() where id='${program}';`); });
it.skipIf(!enabled)("atomically fences same-version imported terms, stores full decisions, and prevents recent repicks", async () => {
 const client = createClient<Database>("http://127.0.0.1:54321", process.env.ONEVOICE_LOCAL_ADMIN!, { auth: { persistSession: false, autoRefreshToken: false } });
 const service = createCampaignService(client, org);
 const decision = await rankOpportunities(await readOpportunityInput(client, org, [product], []));
 const standalone = await rankOpportunities(await readOpportunityInput(client, org, [], []));
 expect(decision.selectedKey).toBe(`product:${product}`); expect(standalone.selectedKey).toBe(`program:${program}`);
 const submit = (selected = decision, revision = 0) => service.fromOpportunity({ id: randomUUID(), requestId: randomUUID(), expectedControlRevision: revision, decision: selected });
 sql(`update public.promotions set discount_value=20 where id='${program}';`);
 await expect(submit()).rejects.toThrow("CONFLICT"); await expect(submit(standalone)).rejects.toThrow("CONFLICT");
 sql(`update public.promotions set discount_value=10,details_text='Changed imported terms' where id='${program}';`);
 await expect(submit()).rejects.toThrow("CONFLICT"); await expect(submit(standalone)).rejects.toThrow("CONFLICT");
 sql(`update public.promotions set details_text=null where id='${program}'; update public.products set price_vnd=600000 where id='${product}';`);
 await expect(submit()).rejects.toThrow("CONFLICT");
 sql(`update public.products set price_vnd=500000 where id='${product}';`);
 sql(`update public.products set name='Different imported product' where id='${product}';`);
 await expect(submit()).rejects.toThrow("CONFLICT");
 sql(`update public.products set name='Local keyboard' where id='${product}';`);
 sql(`update public.promotions set expires_at=clock_timestamp()+interval '2 seconds' where id='${program}';`);
 const expiring = await rankOpportunities(await readOpportunityInput(client, org, [product], []));
 const holder = spawn("docker", ["exec", "-i", "supabase_db_onevoice", "psql", "-X", "-U", "postgres", "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-At"], { windowsHide: true });
 let output = ""; const locked = new Promise<void>(resolve => holder.stdout.on("data", data => { output += data.toString(); if (output.includes("program_locked")) resolve(); }));
 const released = new Promise<void>((resolve, reject) => { holder.on("error", reject); holder.on("exit", code => code === 0 ? resolve() : reject(Error("lock fixture failed"))); });
 holder.stdin.end(`begin;select id from public.promotions where id='${program}' for update;select 'program_locked';select pg_sleep(2.5);commit;`);
 await locked; await expect(submit(expiring)).rejects.toThrow("INVALID"); await released;
 sql(`update public.promotions set expires_at=null where id='${program}';`);
 const malformed = structuredClone(decision) as unknown as { ranked: { operational: object }[] }; malformed.ranked[0].operational = {};
 const invalid = await client.rpc("create_opportunity_campaign", { p_org: org, p_id: randomUUID(), p_request: randomUUID(), p_revision: 0, p_decision: malformed as unknown as Json });
 expect(invalid.error?.code).toBe("22023");
 const id = randomUUID(), requestId = randomUUID();
 const command = { id, requestId, expectedControlRevision: 0, decision };
 expect((await service.fromOpportunity(command)).id).toBe(id); expect((await service.fromOpportunity(command)).id).toBe(id);
 expect(JSON.parse(sql(`select decision from public.campaigns where id='${id}';`))).toEqual(decision);
 expect(sql(`select count(*) from public.campaign_slots where campaign_id='${id}' and scheduled_at is null and content_version_id is null;`)).toBe("1");
 await expect(submit(decision, 1)).rejects.toThrow("CONFLICT");
 expect(sql(`select count(*) from public.campaigns where organization_id='${org}';`)).toBe("1");
 expect(sql(`select count(*) from public.audit_events where organization_id='${org}' and action='campaign.created';`)).toBe("1");
}, 20000);
