import { beforeEach,expect,it,vi } from "vitest";
import type { StaffSession } from "@/lib/auth/session";
const state=vi.hoisted(()=>({actor:null as StaffSession|null,queue:vi.fn(),detail:vi.fn(),transition:vi.fn(),rpc:vi.fn(),client:vi.fn()}));
vi.mock("@/lib/auth/routes",()=>({createAuthContext:async()=>({session:async()=>state.actor,finish:(response:Response)=>response})}));
vi.mock("@/lib/auth/config",()=>({readAuthConfig:()=>({origin:"https://app.test"})}));
vi.mock("@/lib/supabase/server",()=>({createSupabaseDataClient:()=>{state.client();return{rpc:state.rpc};}}));
vi.mock("./read",async importOriginal=>({...await importOriginal<typeof import("./read")>(),createSupportReader:()=>({queue:state.queue,detail:state.detail})}));
vi.mock("../supabase",()=>({createSupabaseConversationRepository:()=>({transition:state.transition})}));
import {GET as queue} from "@/app/api/support/route";
import {GET,POST} from "@/app/api/support/[id]/route";
const id="00000000-0000-4000-8000-000000000015";
const context={params:Promise.resolve({id})};
const input=(operation="claim")=>({operation,expectedRevision:1,requestId:"00000000-0000-4000-8000-000000000016"});
const post=(data:unknown=input(),origin="https://app.test")=>new Request(`https://app.test/api/support/${id}`,{method:"POST",headers:{origin,"content-type":"application/json"},body:JSON.stringify(data)});
beforeEach(()=>{vi.clearAllMocks();state.actor={userId:"00000000-0000-4000-8000-000000000001",organizationId:"a0000000-0000-0000-0000-000000000001",role:"staff",displayName:"Fixture"};state.queue.mockResolvedValue({events:[],counts:{waiting:0,active:0},nextCursor:null});state.detail.mockResolvedValue(null);state.transition.mockResolvedValue({status:"STAFF_ACTIVE",revision:2});state.rpc.mockReturnValue({abortSignal:async()=>({data:{status:"STAFF_ACTIVE"},error:null})});});
it("denies anonymous before private data access",async()=>{state.actor=null;expect((await queue(new Request("https://app.test/api/support"))).status).toBe(401);expect((await POST(post(),context)).status).toBe(401);expect(state.client).not.toHaveBeenCalled();});
it("denies cross-Origin mutations and staff reassignment",async()=>{expect((await POST(post(input(),"https://evil.test"),context)).status).toBe(403);expect((await POST(post({...input("reassign"),assigneeId:id}),context)).status).toBe(403);expect(state.client).not.toHaveBeenCalled();});
it("uses only trusted session scope and protects missing conversation",async()=>{expect((await GET(new Request(`https://app.test/api/support/${id}`),context)).status).toBe(404);expect(state.detail).toHaveBeenCalledWith(state.actor!.organizationId,id,false,undefined);});
it("reuses caller idempotency token and expected revision for double clicks",async()=>{expect((await POST(post(),context)).status).toBe(200);expect((await POST(post(),context)).status).toBe(200);expect(state.transition.mock.calls[0]?.slice(0,3)).toEqual(state.transition.mock.calls[1]?.slice(0,3));expect(state.transition.mock.calls[0]?.[2]).toMatchObject({requestId:input().requestId,expectedRevision:1});});
it("returns409 for a competing state revision",async()=>{state.transition.mockRejectedValue(Error("CONVERSATION_CONFLICT"));expect((await POST(post(),context)).status).toBe(409);});
it("returns403 for non-claimant completion rejected by database",async()=>{state.transition.mockRejectedValue(Error("CONVERSATION_FORBIDDEN"));expect((await POST(post(input("complete")),context)).status).toBe(403);});
it("manager reassignment uses separate audited RPC",async()=>{state.actor={...state.actor!,role:"manager"};expect((await POST(post({...input("reassign"),assigneeId:id}),context)).status).toBe(200);expect(state.rpc).toHaveBeenCalledWith("reassign_conversation_handoff",expect.objectContaining({p_actor_id:state.actor.userId,p_organization_id:state.actor.organizationId,p_assignee_id:id}));expect(state.transition).not.toHaveBeenCalled();});
it("bounds pagination and ignores no untrusted scope override",async()=>{expect((await queue(new Request("https://app.test/api/support?limit=101"))).status).toBe(400);expect((await queue(new Request("https://app.test/api/support?organizationId=other"))).status).toBe(400);expect(state.queue).not.toHaveBeenCalled();});
